### ISSUE TITLE
Link to project page points to https://tochoromero.github.io/aurelia-table/

### ISSUE THREAD

**Issue by aluanhaddad** [tochoromero/aurelia-bootstrap#1]
Hi this looks really cool.

I just want to let you know that currently the `project page` link in the README points to http://tochoromero.github.com/aurelia-table, which looks awesome too, but it is not for this project.

**Comment by tochoromero** [comment]
Thanks for the heads up. I updated the README file, I'm working on the documentation, it should be ready on the next couple of days.

**Comment by aluanhaddad** [comment]
Awesome.

**Comment by aluanhaddad** [comment]
The new project page looks awesome. Thanks!

**Comment by tochoromero** [comment]
Thank you, I have finally created the first release, the documentation is good now :)
