### ISSUE TITLE
Custom CSS class for Tooltip

### ISSUE THREAD

**Issue by wildmichael** [tochoromero/aurelia-bootstrap#14]
I'd like to apply custom styling to _some_ of the tooltips, but since all the tooltips are only children of the `<body>` element, there is no way I can select them. Hence it would be nice if the `aubs-tooltip` had a bindable `class` property allowing the user to add custom classes.

**Comment by tochoromero** [comment]
That sounds like a good idea, I will add that as soon I have a chance.
