### ISSUE TITLE
Incorrect way of calling global options in the docs

### ISSUE THREAD

**Issue by ghiscoding** [tochoromero/aurelia-bootstrap#16]
Hello and thanks for the great plugin, I based myself on your great work to do Custom Element as well. I noticed some typo in your docs and github readme.

First, it seems that Github changed their markdown processor and typing `#Header 1` is no longer and should be written with a space after the `#` so it should be `# Header 1`.  I had to update all of my Github project as well :(
 
Second, I think that your doc is incorrect in [Global Defaults](https://tochoromero.github.io/aurelia-bootstrap/#/defaults). The `:` should be replaced by `=` and the end of each line should be closed accordingly.

For example this:

```javascript
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-bootstrap', config => {
        config.options.accordionCloseOthers: true,
        config.options.accordionGroupPanelClass: 'panel-default',
        ...
    });
```

should be 

```javascript
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-bootstrap', config => {
        config.options.accordionCloseOthers = true;
        config.options.accordionGroupPanelClass = 'panel-default';
        ...
    });
```

Again, thanks for the great work. I'm also starting a set of 3rd party Bootstrap plugins as Custom Element, you might want to take a look [Aurelia-Bootstrap-Plugins](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins). Thanks for helping the community :)

**Comment by tochoromero** [comment]
You are right, I will fix the documentation accordingly, thanks.
