### ISSUE TITLE
How to use with aurelia cli

### ISSUE THREAD

**Issue by rhassler1** [tochoromero/aurelia-bootstrap#2]
What do I need to put in aurelia.json to use this with aurelia cli?

**Comment by tochoromero** [comment]
I'm not very familiar with Aurelia-CLI, I will give it a try and update the documentation

**Comment by tochoromero** [comment]
I have added some documentation for the Aurelia CLI, please let me know if you have any problems.

**Comment by rhassler1** [comment]
It works great. Thanks for the quick response. 

Rich
