### ISSUE TITLE
How to inject variables into custom popovers?

### ISSUE THREAD

**Issue by cjroth** [tochoromero/aurelia-bootstrap#20]
I'm not able to find a way to inject variables into a custom popover. It seems like I should be able to use variables inside of the custom popover template, but that did not work. It does not seem to have access to the view model.

**Comment by tochoromero** [comment]
When doing custom popovers, the Popover element is actually part of your view, it has access to the ViewModel. You don't need to inject anything, you can just access any property or method in your view model.

How are you trying to use it?

**Comment by cjroth** [comment]
I tried that but it doesn't seem to be working - in the Aurelia inspector there were no variables exposed. Basically I did something like this:

```
<div ref="customPopover">
  <div class="popover-contenet">
    ${item.title}
  </div>
</div>
<td class="btn btn-primary" aubs-popover="custom-popover.bind: customPopover;">
  ${item.id}
</td>
```

But `item` is not exposed inside of the popover.

**Comment by tochoromero** [comment]
That looks about right, it should work, I will take a look as soon I have a chance.

**Comment by tochoromero** [comment]
I did some testing, and it is working as expected, I was able to bind to properties in the View Model inside the Custom Popover.

Can you please provide the complete example, maybe we are just missing something.

**Comment by cjroth** [comment]
```
          <div ref="customPopover">
              <h3 class="popover-title">
                  test ${item.created_at}
              </h3>
              <div class="popover-content">${item.id}</div>
          </div>
          <div aubs-popover="custom-popover.bind: customPopover; trigger: click;">${item.id}</div>
```

This is the code. ${item.id} is defined correctly in the triggering div but is undefined in the popover. Any idea?

**Comment by cjroth** [comment]
Oops, figured it out. It gets the variables from where it is defined, not from where it is called. I misunderstood. Thanks @tochoromero for checking on this!

**Comment by tochoromero** [comment]
I'm glad you figured it out :)
