### ISSUE TITLE
Label "for" not working (not passing focus) to aubs-typeahead

### ISSUE THREAD

**Issue by RonaldBastien** [tochoromero/aurelia-bootstrap#21]
`<label for="statusInput">Status</label>`
`<aubs-typeahead` id="statusInput" ...`

When the label element receives focus (e.g. by being clicked on), it does NOT pass the focus on to its associated typeahead control.

**Comment by tochoromero** [comment]
I have an idea on how to implement this, I will give it a try as soon I have a chance. Thanks

**Comment by tochoromero** [comment]
There is a new release that addresses this issue
