### ISSUE TITLE
Support more tooltip positions

### ISSUE THREAD

**Issue by vjsrinath** [tochoromero/aurelia-bootstrap#23]
As of now the the tooltip attribute supports only top, left, right, bottom positions.

It would be very nice if it can support all the possible positions as shown in the following link.

[Tooltip positions](http://github.hubspot.com/tooltip/docs/welcome/)

**Comment by vjsrinath** [comment]
I have raised a pull request for the above requested feature #24 .
Feel free to share your feedback if any :)

**Comment by tochoromero** [comment]
Since Bootstrap 4 beta switched from tether to popper, I need to rework how this works. In the bright side, Popper has more options for positioning and is smarter than Tether.

**Comment by vjsrinath** [comment]
Thanks @tochoromero for the update. I am very much interested in solving this issue or rewrite the tooltip feature using poppers. If you haven't already put up lot of efforts, shall I do and submit a pull request?
