### ISSUE TITLE
Failure to reattach popvers (this.viewModel.attached is not a function)

### ISSUE THREAD

**Issue by Plaristote** [tochoromero/aurelia-bootstrap#28]
I've noticed that when an element that used the aubs-popover custom attribute got detached, and then re-attached, there's a crash that prevents the element from being re-attached properly.

Here's a simple reproducible case : 

```js
// itemWithPopover.js
window.someCondition = true;
export class ItemWithPopover {
  get someCondition() { return window.someCondition; }
}
```

```html
<template>
  <!-- itemWithPopover.html -->
  <div if.bind="someCondition" aubs-popover="custom-
  popover.bind:popover;trigger:click;position:bottom;">
    Click me
  </div>
  <div ref="popover">
    <h3 class="popover-title">Hello world</h3>
  </div>
</template>
```

Use the console to change the value of someCondition from true to false, then back to true to reproduce the issue.

**Comment by tochoromero** [comment]
That is interesting. I will take a look, thanks.
