### ISSUE TITLE
how to suppress javascript warnings?

### ISSUE THREAD

**Issue by guidorice** [tochoromero/aurelia-bootstrap#3]
Hector thanks for aurelia-bootstrap. Really a great plugin! I am noticing some javascript warnings, and I am unsure how to suppress them. Can you suggest anything? I am attaching screenshot because the trace is kind of lengthy. This occurs at the time my `aubs-tabset` and `aubs-tab`s are loaded.

![screen shot 2017-01-17 at 10 06 39 am](https://cloud.githubusercontent.com/assets/766758/22032188/9cf0cc54-dca0-11e6-8f08-c0253239b169.png)

For some reason, the first warning (property-observation) is suppressed when I build with `au build --env prod` but the other two are not.

**Comment by tochoromero** [comment]
Thanks for reporting this.

I managed to get rid of the warning. I created a new release, and I will create a bug against Aurelia Binding, that warning should not appear.

**Comment by guidorice** [comment]
Great- I confirmed the warnings are apparently gone now. Thanks, Alex
