### ISSUE TITLE
Browser autofill is popping up in front of dropdown

### ISSUE THREAD

**Issue by sschocke** [tochoromero/aurelia-bootstrap#32]
Let me start off by saying great job on the library. I have a problem though, and I just want to make sure it's not just something I'm missing before I fix the code and submit a PR for nothing.

TypeAhead Component: 
When the browser's Autofill is enabled, it comes up with it's own popup with suggestions for filling the field. It should be really simple to turn off by adding `autocomplete="off"` to the `<input>` field, but I can't find a way to add it.

Am I missing something?

**Comment by tochoromero** [comment]
You are right, right now there is no way to indicate the plugin to turn off auto complete. We should probably add an attribute to turn it off, it should be very easy.
That said, I have seen chrome ignore that setting, but it is the best we can do.

Would you mind doing a PR with the change?

Thanks

**Comment by tochoromero** [comment]
Already fixed, thanks @sschocke

**Comment by dorle1509** [comment]
I'm using `0.1.20`, and it's not fixed there (using chrome).

I was able to add `autocomplete="off` to the input by using `ref` techniques.

in the html:
`<aubs-typeahead view-model.ref="myVM" ... ></aubs-typeahead>`

and then in `attached()`:

`this.myVM.input.autocomplete = "off";`

but this is an ugly hack - would you accept a PR fixing this in the library?

**Comment by dorle1509** [comment]
@tochoromero 

the code in github and the code in the dist folder of version `0.1.20` is not the same.

in the github you have `autocomplete` binding, and default shoud be `off`:
https://github.com/tochoromero/aurelia-bootstrap/blob/21b8ff061531320683bc66098e4983caff2d4dac/src/typeahead/aubs-typeahead.html#L6-L8

but this is the code in the dist folder is wrong (no matter in wich format in the dist):
        `<input class="form form-control ${inputClass}" placeholder.bind="placeholder" ref="input"
               value.bind="filter & debounce:debounce" disabled.bind="disabled" id.bind="id">`


was it published?
do you plan on publishing a new version soon?

**Comment by sschocke** [comment]
@dorle1509 I don't think the changes I made were ever really merged properly or released. My PR for adding it in was closed with uncommitted changes. I have a copy on my own Github that I have been using that seems to work correctly.

I only use it though for the typeahead component, so I can't take any responsibility if something else is not working. The reason I keep my own branch around is because @tochoromero seems to have abandoned this project.

Feel free to check out my branch if you like https://github.com/ScorpioConcepts/aurelia-bootstrap

**Comment by dorle1509** [comment]
@sschocke Thank you!
your fork looks really nice,
do you plan on publishing it to npm?

**Comment by sschocke** [comment]
@dorle1509 I had never considered it, since I was under the impression that @tochoromero was creating a new fork where he was dropping Bootstrap 3 support entirely and this was the reason for not doing any further work here.

For my current projects I just pull the Github fork in straight from my `package.json`, but I wonder if @tochoromero would be prepared to open up the repo to being managed by a new maintainer, I would consider taking it over.

`package.json` sample:
```json
"dependencies": {
    "aurelia-bootstrap": "github:ScorpioConcepts/aurelia-bootstrap"
}
```
