### ISSUE TITLE
Popover: Element missing when running removeChild in detached

### ISSUE THREAD

**Issue by magnus-hansson** [tochoromero/aurelia-bootstrap#4]
I encountered this issue when using the multiple poop-overs in a tab. 
When navigating away from the page with tabs the line document.body.removeChild(this.popover); causes an error that reads:
Unhandled rejection Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

A simple check for if this element exists before running removeChild removes the error.

Thanks for a great pluging!

**Comment by tochoromero** [comment]
Hello there.
I have not been able to reproduce the issue. The code is already checking if the popover exists before trying to remove it, [here](https://github.com/tochoromero/aurelia-bootstrap/blob/master/src/popover/aubs-popover.js#L63).

I created a page with some tabs, and I added popovers to two tabs. Then I proceed to navigate out of the page, the popovers were removed without a problem.

Would you please provide more information into how reproduce the issue, and please make sure you are running in the latest release.

Thank you for using Aurelia Bootstrap :)

**Comment by magnus-hansson** [comment]
Hello tochoromero, sorry for the delay.
I did a sample project for you to look at if you find the time. 

To replicate the behaviour I get in my real app you just press the reload button in the left hand list.
https://github.com/magnus-hansson/aurelia-cli-contact-manager-custom-poop

I did try to change the detached event to check for the existance of the this.popover before removeChild was run but even though it looked like it could work, after I did the reload I didnt get any popovers at all.

Thanks for your great work.

**Comment by tochoromero** [comment]
I committed a fix, it was an easy one, I just needed to check if the node existed in the body before trying to remove it.

Your use case is one I haven't tested before. You are using the same "custom popover" in multiple places, it is a valid use case, I just never thought about it. 

Thank you very much for reporting the issue, I have created a new release with the fix.
