### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by graycrow** [tochoromero/aurelia-bootstrap#47]
As I can see, there are a few important PR's which are not accepted, last release was more than year ago, BS4 branch is not being developed anymore, etc. So, Is this project abandoned?

**Comment by johntom** [comment]
This is the ugly side of open source, A fantastic repo developed and now you can't even get a response!

**Comment by graycrow** [comment]
Well, I found another [similar project](https://github.com/aurelia-toolbelt/aurelia-toolbelt) which looks like it's under active development and maintainers promptly fixing appearing issues.

**Comment by tochoromero** [comment]
Sorry guys, I will update the readme to indicate this is not active being developed
