### ISSUE TITLE
some feedback about aubs-typeahead

### ISSUE THREAD

**Issue by guidorice** [tochoromero/aurelia-bootstrap#5]
@tochoromero  the `aubs-typeahead` element is working great.  I am using it for it's side effects, basically to add selections to another model, which a multi select menu. 

One thing I could not figure out yet, is how to remove the typed in value upon blur, or in the change.delegate. It seems like the selected value is exposed in the custom element but whatever string is currently typed in cannot be cleared unless the user manually deletes the text.

**Comment by tochoromero** [comment]
Right, I'm really not listening for "external" changes on the selected value, I should probably listen for changes and if it's null just clear the filter. That way you can also set the selected value on load... I will improve that.

**Comment by millerbill3** [comment]
Can you please provide some guidance on how to implement the typeahead component?

**Comment by guidorice** [comment]
@millerbill3 
Here is my very basic usage of it, it follows aurelia conventions for custom components, so I mostly figured this out by looking at the source to see what bindings it has. In an aurelia template I wrote:
```
<aubs-typeahead
      value.bind="generaTypeahead"
      data.bind="genera"
      input-class="typeahead-input-lg"
      change.delegate="onGeneraTypeahead(generaTypeahead)"
      placeholder="enter a genus">
</aubs-typeahead>
```
The only trick is the data array needs to be objects with a 'name' property, not just an array of strings.

**Comment by tochoromero** [comment]
Sorry guys, writting the documentation is on my to-do list, I just haven't had the chance

**Comment by guidorice** [comment]
@tochoromero n.p. thanks again for adding this great feature!

**Comment by millerbill3** [comment]
Thanks for the quick response!!!!

**Comment by guidorice** [comment]
One additional observation, and please let me know if I should open a new issue for this:
when selecting an item with a mouse click (i.e. not selecting with keyboard arrow keys + ENTER), the value passed to the change delegate is actually null the first time, and only the second (or even third attempt) the value is set to the correct selected value. It seems almost as if there is a disconnect between the change event and the value model, and it takes a couple of attempts to get the component 'primed'.

**Comment by millerbill3** [comment]
Ok, thanks for the update... I'll let you know

**Comment by tochoromero** [comment]
Please create a new issue for the event problem.

**Comment by millerbill3** [comment]
Ok, I'm assuming "data.bind" is where I refer to my array of country objects from my model? I'm getting an error: Cannot read property "length" of undefind.

**Comment by tochoromero** [comment]
It seems the property you are using in data.bind is undefined. Make sure you initialize the array (even to an empty array)  from the get go.

**Comment by millerbill3** [comment]
Ok, got it... The bug is there though. It's like you said earlier... you have to select the value twice before it's passed to the controller/view model. The first time `undefined` is passed. The second you actually get the value.

**Comment by tochoromero** [comment]
I have made some tweaks to the plugin, and I have also written the documentation. Please check it out.
I will close this issue for now. If after the update and following the documentation you still see this issue please reopen.

**Comment by millerbill3** [comment]
Thanks, I'll check it out tonight.
