### ISSUE TITLE
possible platform difference with aubs-typeahead

### ISSUE THREAD

**Issue by guidorice** [tochoromero/aurelia-bootstrap#6]
I noticed that on Chrome and Firefox, I can select results with ENTER/RETURN keypress, but on Safari and IE11, the keypress method of selection doesnt work forcing a mouse click to make a selection.

**Comment by tochoromero** [comment]
I wonder if the key code is different for those browsers, I can check with safari, but not with IE. Will take  a look.

**Comment by tochoromero** [comment]
I have made some tweaks to the plugin, and I have also written the documentation. Please check it out.
I will close this issue for now. If after the update and following the documentation you still see this issue please reopen.

**Comment by guidorice** [comment]
it's working perfectly. thanks again for this great custom element.
