### ISSUE TITLE
aubs-typeahead: selecting items with mouse click

### ISSUE THREAD

**Issue by guidorice** [tochoromero/aurelia-bootstrap#7]
One additional observation, possibly a bug, so far seen with chrome and safari (that is all I have tested for this today).

When selecting an item with a mouse click (i.e. not selecting with keyboard arrow keys + ENTER), the value passed to the change delegate is actually null the first time, and not until the second (or sometimes even third attempt) the value is set to the correct selected value. It seems almost as if there is a disconnect between the change event and the value model, and it takes a couple of attempts to get the component 'primed'. 

Thanks much for looking into this! I hope to dig into the source more as well, will post here or make a pull request if I come up with any improvements.

**Comment by guidorice** [comment]
Also here is how I am instantiating the element:
```
<aubs-typeahead
          id="samples-typeahead"
          value.bind="sampleTypeahead"
          data.bind="samples"
          input-class="typeahead-input-lg"
          change.delegate="onSampleTypeahead(sampleTypeahead)"
          placeholder="enter a sample name">
</aubs-typeahead>
```

**Comment by tochoromero** [comment]
So... I didn't implement the change event at all... I assume what you are getting is the bubbled event from the input itself...
I should probably trigger a custom event for changes. 
On the main while you can observe the value property for changes.

**Comment by tochoromero** [comment]
I have made some tweaks to the plugin, and I have also written the documentation. Please check it out.
I will close this issue for now. If after the update and following the documentation you still see this issue please reopen.

**Comment by guidorice** [comment]
thanks! confirmed selecting items with mouse click is working perfect in aurelia-bootstrap@0.1.14
