### ISSUE TITLE
Typeahead fails to populate value when initially selected

### ISSUE THREAD

**Issue by millerbill3** [tochoromero/aurelia-bootstrap#8]
When you select a value from the list of filtered options (keyboard or mouse click) the `change.delegate` is invoked and calls the method defined within the view model, but the bound value is `undefined` the first time. Subsequent selections from the filtered list of options will successfully pass the selected value as an argument to the defined method every other time.
Steps to reproduce:

1. Initialized the widget on the page
2. Place a console.log instruction in your callback method within the view model to log out the passed argument value.
3. Begin typing in the field and select one of the filtered values in the displayed list (either mouse-click or keyboard selection)
4. Observe the console in the browser. The first selection will show `undefined`. The second time a selection is made the selected value will be logged in the console.
5. Now repeat steps 3 & 4 and you'll notice that every other time you select a value the value is output in the console.

**Comment by tochoromero** [comment]
Duplicates #7
